org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod
version=1.1.0
group=com.chaos
mod_id=chaosgravestone
mod_name=Chaos Gravestone
mod_author=Luis Enrique Gil Mayser
license=MIT
java_version=21

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.21.5)

# common: Minecraft vanilla (sin cargador) vía NeoForm
neo_form_version=1.21.4-20241203.161809

# Fabric (https://fabricmc.net/develop)
loom_version=1.18.2
loader_version=0.19.5
fabric_api_version=0.119.4+1.21.4

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
moddev_version=2.0.148
neoforge_version=21.4.158
neoforge_loader_version_range=[4,)
